font_family mononoki
font_size 12
window_margin_width 8
map ctrl+c copy_or_interrupt
map ctrl+v paste_from_clipboard

# Kitty has a crap-ton of fun options to play around with,
# see https://sw.kovidgoyal.net/kitty/conf/